- set_fact:
    technique: "{{ item }}"

- debug:
    var: technique

- name: Start threat capture with CAP Attack
  win_shell: |
    Import-Module "C:\Program Files\ansible\capattack\capattack-ps\capattack.psd1" -Force
    CapAttack-Start
  when: cap_attack == "1"
  ignore_errors: True

- name: Get requirements for Atomic Red Team Technique
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -GetPrereqs
  register: requirements
  ignore_errors: True

- name:  Run specified Atomic Red Team Technique
  win_shell: |
    Set-ExecutionPolicy bypass
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -Confirm:$false -TimeoutSeconds 300 -ExecutionLogPath C:\AtomicRedTeam\atc_execution.csv
  register: output_art
  ignore_errors: True

- debug:
    var: output_art.stdout_lines

- name: Stop threat capture with CAP Attack and upload
  win_shell: |
    Import-Module "C:\Program Files\ansible\capattack\capattack-ps\capattack.psd1" -Force
    CapAttack-Stop -Headless -Upload 
  when: cap_attack == "1" and cap_attack_upload_threat_capture == "1"

- name: Stop threat capture with CAP Attack
  win_shell: |
    Import-Module "C:\Program Files\ansible\capattack\capattack-ps\capattack.psd1" -Force
    CapAttack-Stop -Headless 
  when: cap_attack == "1" and cap_attack_upload_threat_capture == "0"

- name: Cleanup after execution
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -Cleanup
  register: cleanup

