[General]
# supported options: attacker,victim
machine_type=victim
# Name displayed in metadata (Optional)
display_name=
# Perform auto updates
autoupdate=true
# Capture without a user session
headless=false

[Logging]
### ATTACKER/VICTIM OPTIONS ###
# Records desktop with ffmpeg
desktop=true

# Windows capture device options: gdigrab,dshow
# Note: Windows only
ffmpeg_recorder=gdigrab

# Records keystrokes
keystrokes=false


##### VICTIM ONLY OPTIONS #####
# how to pull event logs from the system
# supported options include: raw, xml (deprecated)
# Note: windows only
log_format=raw

# clear event logs prior to session start
# Note: windows only
clear_event_logs=true

# supported options include: sysmon, none
edr=sysmon

# sysmon configuration to use; placed in same directory as this script
# Note: Windows only
sysmon_config=sysmon_snapattack.xml

# Configures audit policy logs, such as 4688
# Note: Windows only
auditpol=true

# configures PowerShell v5 module and script block logging
# Note: Windows only
powershell_module_scriptblock=true

# Configures packet capture - Can use win10pcap or npcap
# Note: windows only
pcap=true
pcap_driver=win10pcap
